---
- hosts: all
  become: yes

  tasks:
  - name: Disable SELinux
    selinux: state=disabled

  - name: Add HashiCorp yum repo
    yum_repository:
      name: hashicorp
      description: "Hashicorp Stable - $basearch"
      baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
      gpgkey: "https://rpm.releases.hashicorp.com/gpg"
      gpgcheck: yes
      enabled: yes

  - name: Install packages
    yum:
      name:
        - consul
        - nomad
        - unbound
      state: latest

  - name: Install docker
    include_tasks: "docker.yml"
    when: role == "client"

  - name: Configure consul
    template: src="consul-{{ role }}.hcl.j2" dest="/etc/consul.d/consul.hcl"
    notify: "reload consul"

  - name: Configure nomad
    template: src="nomad-{{ role }}.hcl.j2" dest="/etc/nomad.d/nomad.hcl"
    notify: "restart nomad"


  - name: Configure consul forwarding in unbound
    template: src="unbound-consul.conf.j2" dest="/etc/unbound/conf.d/consul.conf"
    notify: "restart unbound"

  # the following 2 tasks will move all nameservers besides 127.0.0.1 to unbound config
  - name: Get nameservers in resolv.conf
    shell: grep ^nameserver /etc/resolv.conf | awk '{print $2}' | uniq | grep -v 127.0.0.1 || true
    register: nameservers

  - name: Configure forwarders in unbound
    template: src="unbound-forwarders.conf.j2" dest="/etc/unbound/conf.d/forwarders.conf"
    when: nameservers.stdout_lines | length
    notify: "restart unbound"

  - name: Send DNS requests to local unbound
    copy: dest="/etc/resolv.conf" content="nameserver 127.0.0.1\n"


  - name: Flush handlers
    meta: flush_handlers

  - name: Ensure services are enabled and running
    systemd: name="{{ item }}" enabled=yes state=started
    with_items:
      - consul
      - nomad
      - unbound

  - name: Servers list
    debug: msg="{{ groups['servers'] | map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) }}"
    run_once: yes


  handlers:
  - name: reload consul
    systemd:
      name: "consul"
      state: reloaded

  - name: restart nomad
    systemd:
      name: "nomad"
      state: restarted

  - name: restart unbound
    systemd:
      name: "unbound"
      state: restarted
